//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeAtendimento.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conversa()
        {
            this.Mensagens = new HashSet<Mensagens>();
        }
    
        public int IdConversa { get; set; }
        public string ConsultorId { get; set; }
        public Nullable<int> VisitanteId { get; set; }
        public Nullable<System.DateTime> dataConversa { get; set; }
        public string tempoConversa { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Visitante Visitante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagens> Mensagens { get; set; }
    }
}
