//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeAtendimento.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacoes
    {
        public int IdNotificacao { get; set; }
        public string MensagemNotificacao { get; set; }
        public Nullable<int> ConversaId { get; set; }
        public string ConsultorId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
